### ISSUE TITLE
User Can View Plans Offered

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/Messages-From-Heaven#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can View the available services  and a description of each

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be presented with a list of the plans available and the features of each, they will have the ability to add either of them to the cart and  check out 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Messages From Heaven – Figma - Google Chrome 1_18_2024 3_02_54 PM](https://github.com/Eric-Fried/Messages-From-Heaven/assets/146288203/af30d6c3-b69a-4711-b85d-031e5da26cbc)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add endpoint (get /api/plans)  to server for getting plans. 
      - [ ] (use sgt backend as example)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component that will perform a get request and render the results 
    - [x]  rendering lists 
    - [x] use react routing as example for how 
- [x] add route for plans page
