### ISSUE TITLE
User can purchase a plan and set their message to send 

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/Messages-From-Heaven#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can purchase their plan (paid or free) and set the message to be sent to their child 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the panel for the plan they wish to buy they will enter the details of their plan into a form and then click "Buy"

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to perform a POST request (add endpoint) to add the data from the form component to the database (sgt backend, code journal backend)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a form to take in plan details 
- [x] onClick of buy button submit the form (react form component , fetch in react practice )  
- [x] perform fetch request(post) to database
