### ISSUE TITLE
User Can Sign in /Sign out / Sign up 

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/Messages-From-Heaven#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in or create an account 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will click sign up and be directed to a sign up page that allows them to sign up or sign in if they have an existing account 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] add post endpoint to server to store username and password to database (sign up)
     - [x] api registration
- [x] add post endpoint to server to sign in user 
     - [x] authentification 
- [x] use authMiddleware 
    - [x] authorization
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] create sign in form 
   - [x] uncontrolled form and api authorization/authenification
   - [x] fetch request  to log in user 
- [x] create sign up form 
   - [x] uncontrolled form and api authorization/authenification
   - [x] fetch request to post new user and hashed password to database
- [x] make sure user is signed in before allowing purchase of plan 
     - [x] authorization
