### ISSUE TITLE
User can sign up to be a donor 

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/Messages-From-Heaven#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to sign up to be a donor for the messages from heaven program and will be able to donate funds that will go to a financially needy terminal parent 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will be presented with a form that is similar to the  form used for purchasing a plan but that form will sign them up to be a donor 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to contain a donors table with similar columns as users
- [x] Update `data.sql` to contain the proper preset values

### ☁️ Server Tasks

- [ ] Update `server.js` to perform a POST request (add endpoint) to add the data from the form component to the database (sgt backend, code journal backend)
- [ ] update 'server.ts' to perform a get request for all donor plans available 
- [ ] update 'server.ts' to perform a get request for individual donor plans 
- [ ] update 'server.ts' to perform a post request for adding purchase to donor table
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create purchase form to take in donors details
- [ ] Create donor catalog
- [ ] onClick of Donate button submit the form (check purchase form)
- [ ] perform fetch request (post) to database (inside donor purchase form)
